name: Generate a Flutter application template

on: [push]

jobs:
  rename-project:
    if: ${{ github.repository	!= 'solid-software/project-template' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash

      - name: Get Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
  
      - name: Rename the project
        run: |
          echo "Creating the project with org com.${{ env.REPOSITORY_OWNER }}.${{ env.REPOSITORY_NAME }} name ${{ env.REPOSITORY_NAME }}"
          flutter create . --org="com.${{ env.REPOSITORY_OWNER }}.${{ env.REPOSITORY_NAME }}" --project-name="${{ env.REPOSITORY_NAME }}"
          flutter pub add --dev solid_lints
          flutter pub get
      
      - name: Self-destruct
        run: |
          rm .github/workflows/generate-template.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          # commit_options: '--amend --no-edit'
          push_options: --force

